#!/bin/sh

# PROVIDE: PuraVidaCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# PuraVidaCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable PuraVidaCoin service.
# PuraVidaCoin_config (path): Set to /usr/local/etc/PuraVidaCoin.conf by default.
# PuraVidaCoin_user:  The user account PuraVidaCoin daemon runs as. It uses 'root' user by default.
# PuraVidaCoin_group: The group account PuraVidaCoin daemon runs as. It uses 'wheel' group by default.
# PuraVidaCoin_datadir (str): Default to "/var/db/PuraVidaCoin". Base data directory.

. /etc/rc.subr

name=PuraVidaCoin
rcvar=PuraVidaCoin_enable

: ${PuraVidaCoin_enable:=NO}
: ${PuraVidaCoin_config=/usr/local/etc/PuraVidaCoin.conf}
: ${PuraVidaCoin_datadir=/var/db/PuraVidaCoin}
: ${PuraVidaCoin_user="root"}
: ${PuraVidaCoin_group="wheel"}

required_files=${PuraVidaCoin_config}
command=/usr/local/bin/PuraVidaCoind
PuraVidaCoin_chdir=${PuraVidaCoin_datadir}
pidfile="${PuraVidaCoin_datadir}/PuraVidaCoind.pid"
stop_cmd=PuraVidaCoin_stop
command_args="-conf=${PuraVidaCoin_config} -datadir=${PuraVidaCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

PuraVidaCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${PuraVidaCoin_datadir}
	[ $? -eq 0 ] && chown -R ${PuraVidaCoin_user}:${PuraVidaCoin_group} ${PuraVidaCoin_datadir}
}

PuraVidaCoin_prestart()
{
	if [ ! -d "${PuraVidaCoin_datadir}/." ]; then
		PuraVidaCoin_create_datadir || return 1
	fi
}

PuraVidaCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

PuraVidaCoin_stop()
{
    PuraVidaCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${PuraVidaCoin_config} -datadir=${PuraVidaCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
